[profile.default]
ffi = true
ast = true
build_info = true
extra_output = ["storageLayout"]
optimizer = true
optimizer_runs = 999999

solc_version = "0.8.22"
evm_version = "london"

allow_unused_prank = true

fs_permissions = [{ access = "read-write", path = "./"}]

[rpc_endpoints]
memo-dev = ""
memo-product = ""
memo-test = ""